name: CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo código
        uses: actions/checkout@v4.1.5
      - name: autenticação no docker hub 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: build da imagem
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
           marcossousalima/aula-primeira-pipeline:v${{ github.run_number}} 
           marcossousalima/aula-primeira-pipeline:latest  
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Obtendo codigo
        uses: actions/checkout@v4.1.5
      - name: Configuração de contextodo kubernetes
        uses: azure/k8s-set-context@v4.0.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S }} 
      # - name: Execucao do manifesto
      #   uses: Azure/k8s-deploy@v5
      #   with:
      #     manifests: |
      #       ./k8s/deployment.yaml
      #     images: |
      #       marcossousalima/aula-primeira-pipeline:v${{ github.run_number}}

