name: CI-CD
on:
  push: 
    branches: [main]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-lastest
    steps:
    - name: Obtendo código
      uses: actions/checkout@v4.1.5
    - name: autenticação no docker hub 
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
